# Generated by Django 5.0.6 on 2024-05-27 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('numUsuario', models.IntegerField()),
                ('NIF', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idLibro', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=30)),
                ('Editorial', models.CharField(max_length=60)),
                ('NumPags', models.SmallIntegerField()),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecPrestamo', models.DateTimeField()),
                ('fecDevolucion', models.DateTimeField()),
                ('idLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
    ]
